version: "3"

services:
  php:
    image: php:7.2-apache
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    ports:
      - 8000:80
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
